// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaSlA96mo4GoPuDBNQCJBphcX_-00z8Qw',
    appId: '1:1004887358828:web:18a1486fecde3764c74749',
    messagingSenderId: '1004887358828',
    projectId: 'mybookingapp-99fcf',
    authDomain: 'mybookingapp-99fcf.firebaseapp.com',
    storageBucket: 'mybookingapp-99fcf.firebasestorage.app',
    measurementId: 'G-SYE5PC19DW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOsT8wTCsEU0_f_-sLMbeSAPyMko1bWq0',
    appId: '1:1004887358828:android:255c1111152388ffc74749',
    messagingSenderId: '1004887358828',
    projectId: 'mybookingapp-99fcf',
    storageBucket: 'mybookingapp-99fcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOvqjsDzdCzWzGmMVgUYo9AX8xpTiIsAA',
    appId: '1:1004887358828:ios:b1447c31f6ddf552c74749',
    messagingSenderId: '1004887358828',
    projectId: 'mybookingapp-99fcf',
    storageBucket: 'mybookingapp-99fcf.firebasestorage.app',
    iosBundleId: 'com.example.myBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOvqjsDzdCzWzGmMVgUYo9AX8xpTiIsAA',
    appId: '1:1004887358828:ios:b1447c31f6ddf552c74749',
    messagingSenderId: '1004887358828',
    projectId: 'mybookingapp-99fcf',
    storageBucket: 'mybookingapp-99fcf.firebasestorage.app',
    iosBundleId: 'com.example.myBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaSlA96mo4GoPuDBNQCJBphcX_-00z8Qw',
    appId: '1:1004887358828:web:1bda2bb681e0a27ac74749',
    messagingSenderId: '1004887358828',
    projectId: 'mybookingapp-99fcf',
    authDomain: 'mybookingapp-99fcf.firebaseapp.com',
    storageBucket: 'mybookingapp-99fcf.firebasestorage.app',
    measurementId: 'G-V7N4KGR8C5',
  );
}
